emart/cart/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.cart, name = "cart"),
    
    path("add_cart/<int:product_id>/", views.add_cart, name = "add_cart"),
    path("sub_cart/<int:product_id>/<int:cart_item_id>/", views.sub_cart, name = "sub_cart"),
    path("remove_cart/<int:product_id>/<int:cart_item_id>/", views.remove_cart, name = "remove_cart"),

    path("checkout", views.checkout, name = "checkout"),

]

emart/emart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("eapp.urls")), 
    path("store/", include("store.urls")),
    path("cart/", include("cart.urls")),
    path("accounts/", include("accounts.urls")),
    path("orders/", include("orders.urls")),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

emart/store/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.store, name="store"),
    path("categories/<slug:category_slug>/", views.store, name="products_by_categories"),
    path("categories/<slug:category_slug>/<slug:product_slug>/", views.product_detail, name="product_detail"),
    path("search/", views.search, name="search"),
    path("submit_review/<int:product_id>/", views.submit_review,name="submit_review"),
]

emart/store/models.py
from eapp.models import Category, Account
from django.db import models
from django.urls import reverse
from django.db.models import Avg, Count
# Create your models here.

class Product(models.Model):
    product_name        = models.CharField(max_length=200, unique=True)
    slug                = models.SlugField(max_length=100, unique=True)
    description         = models.TextField(max_length=200, unique=True)
    price               = models.IntegerField()
    stock               = models.IntegerField()
    image               = models.ImageField(upload_to="static/images")
    is_available        = models.BooleanField(default=True)
    category            = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date        = models.DateTimeField(auto_now_add=True)
    modified_date       = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse("product_detail",args=[self.category.slug,self.slug])


    def __str__(self):
        return self.product_name

    def averagereview(self):
        reviews = ReviewRating.objects.filter(product=self,status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg

    def countreview(self):
        reviews = ReviewRating.objects.filter(product=self,status=True).aggregate(count=Count('id'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count


class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color',is_active=True)
        
    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size',is_active=True)


variation_category_choice = (
    ('color','color'),
    ('size','size')
)

class Variation(models.Model):
    product             = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category  = models.CharField(max_length=50, choices = variation_category_choice )
    variation_value     = models.CharField(max_length=50)
    is_active           = models.BooleanField(default=True)
    created_date        = models.DateTimeField(auto_now=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value


class ReviewRating(models.Model):
    product             = models.ForeignKey(Product, on_delete=models.CASCADE)
    user                = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject             = models.CharField(max_length=100, blank = True)
    review              = models.TextField(max_length = 500, blank = True)
    rating              = models.FloatField()
    ip                  = models.CharField(max_length=100, blank = True)
    status              = models.BooleanField(default=True)
    created_date        = models.DateTimeField(auto_now_add=True)
    udated_date         = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject


class ProductGallery(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='static/images/product_gallery',max_length=255)

    def __str__(self):
        return self.product.product_name
    
    class Meta:
        verbose_name= 'ProductGallery'
        verbose_name_plural = 'productgalleries'

emart/store/forms.py
from django import forms
from .models import ReviewRating

class ReviewRatingForm(forms.ModelForm):
    class Meta:
        model  = ReviewRating
        fields = ['subject', 'rating', 'review']

emart/store/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from django.contrib import messages, auth
from .models import Product, ReviewRating, ProductGallery
from orders.models import OrderProduct
from eapp.models import Category
from cart.models import Cart_item
from cart.views import _cart_id
from .forms import ReviewRatingForm
from django.http import HttpResponse
from eapp.models import Account, UserProfile

from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
# Create your views here.

def store(request,category_slug=None):
    categories  = None
    products    = None

    if category_slug != None :
        categories  = get_object_or_404(Category, slug=category_slug)
        products    = Product.objects.filter(category=categories,is_available=True)


    else:
        products    = Product.objects.all().filter(is_available=True)
    
    for product in products:
        reviews = ReviewRating.objects.filter(product_id=product.id, status=True)

    paginator   = Paginator(products,6)
    page        = request.GET.get("page")
    paged_products = paginator.get_page(page)
    
    product_count = products.count()
    context = {
        "products"      : paged_products,
        "product_count" : product_count,
        "reviews"       : reviews
    }
    return render(request, 'store/store.html', context)


def product_detail(request, category_slug, product_slug):
    try:
        single_product  = Product.objects.get(category__slug=category_slug,slug=product_slug)
        in_cart         = Cart_item.objects.filter(cart__cart_id=_cart_id(request), product=single_product).exists()


    except Exception as e:
        raise e

    if request.user.is_authenticated:
        try :
            orderproduct = OrderProduct.objects.filter(user=request.user,product_id=single_product.id).exists()
        except orderproduct.DoesNotExist:
            orderproduct = False
    else:
        orderproduct = False
    


    # get the reviews
    reviews = ReviewRating.objects.filter(product_id=single_product.id, status=True)
    user = request.user
    userlog = user.is_authenticated
    if userlog :
        # userprofile = get_object_or_404(UserProfile, user = user)
        try:
            userprofile = UserProfile.objects.get(user_id = user.id)
        except:
            userprofile = None
    else :
        userprofile = None


    # get the product gallery
    product_gallery = ProductGallery.objects.filter(product_id=single_product.id)

    context ={
        'single_product'    :single_product,
        'in_cart'           :in_cart,
        'orderproduct'      :orderproduct,
        'reviews'           :reviews,
        'product_gallery'   :product_gallery,
        # 'userprofile'       :userprofile,
        }

    return render(request,"store/product_detail.html",context)

def search(request):
    if 'keyword' in request.GET:
        keyword = request.GET["keyword"]
        if keyword:
            products    = Product.objects.order_by('-created_date').filter(Q(description__icontains=keyword) | Q(product_name__icontains=keyword))
    product_count   = products.count()

    context={
        "products"      :   products,
        "product_count" :   product_count
    }

    return render(request,"store/store.html",context)


def submit_review(request, product_id):
    url = request.META.get('HTTP_REFERER')
    user = request.user
    if request.method == 'POST':
        try: 
            review = ReviewRating.objects.get(user__id=user.id,product__id=product_id)
            form = ReviewRatingForm(request.POST, instance=review)
            form.save()
            messages.success(request,'Thank you. Your review has been updated.')
            
        
        except ReviewRating.DoesNotExist:
            form = ReviewRatingForm(request.POST)
            if form.is_valid():
                data = ReviewRating()
                data.subject = form.cleaned_data['subject']
                data.review = form.cleaned_data['review']
                data.rating = form.cleaned_data['rating']
                data.ip = request.META.get('REMOTE_ADDR')
                data.product_id = product_id
                data.user_id = request.user.id
                data.save()
                messages.success(request, 'Thank you. Your review has been submitted. ')
    return redirect(url)

emart/templates/store/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="section-content padding-y bg">
<div class="container">

<!-- ========================= SECTION CONTENT START// ========================= -->


<!-- ============================ COMPONENT 1 ================================= -->
<div class="card">
	<div class="row no-gutters">
		<aside class="col-md-6">
			<article class="gallery-wrap"> 
				<div class="img-big-wrap mainImage">
				<center><a href="#"><img src="{{single_product.image.url}}"></a></center>
				</div> <!-- img-big-wrap.// -->
				
			</article> <!-- gallery-wrap .end// -->
			<ul class="thumb">
			<li class="d-flex">
			<a href="{{single_product.image.url}}" target="mainImage"><img src="{{single_product.image.url}}"></a>
			{% for i in product_gallery %}
			<a href="{{i.image.url}}" target="mainImage">
			<img src="{{i.image.url}}" alt="Product Image" style="width:80px; height:80px; object-fit:cover;"></a>
			{% endfor %}
			</li>
			</ul>
		</aside>
		<main class="col-md-6 border-left">
<article class="content-body">

<h2 class="title">{{single_product.product_name}}</h2>
<span style="color:#ffb503;">
	<i class="fa fa-star{% if single_product.averagereview >= 0.5 and single_product.averagereview < 1 %}-half-o{% elif single_product.averagereview < 0.5 %}-o{% endif %}" aria-hidden="true"></i>
	<i class="fa fa-star{% if single_product.averagereview >= 1.5 and single_product.averagereview < 2 %}-half-o{% elif single_product.averagereview < 1.5 %}-o{% endif %}" aria-hidden="true"></i>
	<i class="fa fa-star{% if single_product.averagereview >= 2.5 and single_product.averagereview < 3 %}-half-o{% elif single_product.averagereview < 2.5 %}-o{% endif %}" aria-hidden="true"></i>
	<i class="fa fa-star{% if single_product.averagereview >= 3.5 and single_product.averagereview < 4 %}-half-o{% elif single_product.averagereview < 3.5 %}-o{% endif %}" aria-hidden="true"></i>
	<i class="fa fa-star{% if single_product.averagereview >= 4.5 and single_product.averagereview < 5 %}-half-o{% elif single_product.averagereview < 4.5 %}-o{% endif %}" aria-hidden="true"></i>
</span>

<div class="mb-3"> 
	<var class="price h4">${{single_product.price}}</var> 
</div> 

<p>{{single_product.description}}</p>


<hr>
<form action="{% url 'add_cart' single_product.id %}" method="POST">
{% csrf_token %}
	<div class="row">
		<div class="item-option-select">
			<h6>Choose Color</h6>
			<select name="color" class="form-control" required>
				<option value="" disabled selected>select</option>
				{% for i in single_product.variation_set.colors %}
					<option value="{{i.variation_value}}">{{i.variation_value}}</option>
				{% endfor %}
				
			</select>
		</div>
	</div> <!-- row.// -->
	<div class="row">
		<div class="item-option-select">
			<h6>Select Size</h6>
			<select name="size" class="form-control" required> 
				<option value="" disabled selected>select</option>
				{% for i in single_product.variation_set.sizes %}
					<option value="{{i.variation_value}}">{{i.variation_value}}</option>
				{% endfor %}
			</select>
		</div>
	</div> <!-- row.// -->
	<hr>
    {% if single_product.stock <= 0 %}
    	<h4 class="text-danger">Out of stock</h4><br>
        <h4 class="text-warning">comming soon</h4>
    {% else %}
        <h4 class="text-success">Available</h4>

        {% if single_product.stock == 1 %}
            <h4 class="text-warning">Only 1 is in stock</h4>
        {% else %}
            <h4 class="text-warning">Only {{single_product.stock}} are in stock</h4>
        {% endif %}

		{% comment %} {% if in_cart %}
			<a href="{% url 'add_cart' single_product.id %}" class="btn  btn-success"> <span class="text">Added to cart</span> <i class="fas fa-check"></i>  </a>
			<a href="{% url 'add_cart' single_product.id %}" class="btn  btn-outline-primary"> <span class="text">View Cart</span> <i class="fas fa-eye"></i>  </a>
		{% else %} {% endcomment %}
	 		<button class="btn  btn-primary"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i>  </button>
		{% comment %} {% endif %} {% endcomment %}
	{% endif %}
</form>
</article> <!-- product-info-aside .// -->
		</main> <!-- col.// -->
	</div> <!-- row.// -->
</div> <!-- card.// -->
<!-- ============================ COMPONENT 1 END .// ================================= -->

<br>

<div class="row">
			<div class="col-md-9">

	<form action = "{% url 'submit_review' product_id=single_product.id %}" method ="POST">
	{% csrf_token %}
	<h5> Write Your Review</h5>
	{% include "includes/alert.html" %}
	<div>
		<label> How do you rate this product?</label>
		<br>
		<div class="rate">
			<input type="radio" name="rating" id="rating10" value="5" required/><label for="rating10" title="5"></label>
			<input type="radio" name="rating" id="rating9" value="4.5" required/><label for="rating9" title="4.5" class="half"></label>
			<input type="radio" name="rating" id="rating8" value="4" required/><label for="rating8" title="4"></label>
			<input type="radio" name="rating" id="rating7" value="3.5" required/><label for="rating7" title="3.5" class="half"></label>
			<input type="radio" name="rating" id="rating6" value="3" required/><label for="rating6" title="3"></label>
			<input type="radio" name="rating" id="rating5" value="2.5" required/><label for="rating5" title="2.5" class="half"></label>
			<input type="radio" name="rating" id="rating4" value="2" required/><label for="rating4" title="2"></label>
			<input type="radio" name="rating" id="rating3" value="1.5" required/><label for="rating3" title="1.5" class="half"></label>
			<input type="radio" name="rating" id="rating2" value="1" required/><label for="rating2" title="1"></label>
			<input type="radio" name="rating" id="rating1" value="0.5" required/><label for="rating1" title="0.5" class="half"></label>
		</div>
		<br>
		Review Title :
		<input type="text" class="form-control" name="subject">
		<br>
		Review :
		<input type="textarea" class="form-control" name="review">
		<br>
		{% if user.is_authenticated %}
			{% if orderproduct is False %}
				You need to purchase the product to submit your review.
			{% else %}
				<input type="submit" class="btn btn-primary" valure="submit review">
			{% endif %}
		{% else %}
		You need to <a href="{% url 'login' %}"> login </a>to submit your review.
		{% endif %}
	</div>
	</form>
	<header class="section-heading">
		<h3>Customer Reviews </h3>  
		<span style="color:#ffb503;">
			<i class="fa fa-star{% if single_product.averagereview >= 0.5 and single_product.averagereview < 1 %}-half-o{% elif single_product.averagereview < 0.5 %}-o{% endif %}" aria-hidden="true"></i>
			<i class="fa fa-star{% if single_product.averagereview >= 1.5 and single_product.averagereview < 2 %}-half-o{% elif single_product.averagereview < 1.5 %}-o{% endif %}" aria-hidden="true"></i>
			<i class="fa fa-star{% if single_product.averagereview >= 2.5 and single_product.averagereview < 3 %}-half-o{% elif single_product.averagereview < 2.5 %}-o{% endif %}" aria-hidden="true"></i>
			<i class="fa fa-star{% if single_product.averagereview >= 3.5 and single_product.averagereview < 4 %}-half-o{% elif single_product.averagereview < 3.5 %}-o{% endif %}" aria-hidden="true"></i>
			<i class="fa fa-star{% if single_product.averagereview >= 4.5 and single_product.averagereview < 5 %}-half-o{% elif single_product.averagereview < 4.5 %}-o{% endif %}" aria-hidden="true"></i>
		<span style="color:black;"> ({{single_product.countreview}})</span>
		</span>
	</header>

	<article class="box mb-3">

	{% for review in reviews %}
		<div class="icontext w-100">
			{% comment %} <img src="{% static {{userprofile.profile_picture.url}} %}" class="img-xs icon rounded-circle"> {% endcomment %}
			{% comment %} <img src="{{userprofile.profile_picture.url}}" class="img-xs icon rounded-circle"> {% endcomment %}
			<div class="text">
				<span class="date text-muted float-md-right">{{review.updated_at}}</span>  
				<h6 class="mb-1">{{review.user.first_name}} {{review.user.last_name}}</h6>
				<div>
				<span style="color:#ffb503;">
					<i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o{% endif %}" aria-hidden="true"></i>
					<i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o{% endif %}" aria-hidden="true"></i>
					<i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o{% endif %}" aria-hidden="true"></i>
					<i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o{% endif %}" aria-hidden="true"></i>
					<i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o{% endif %}" aria-hidden="true"></i>
				</span>
				</div>
				
			</div>
		</div> <!-- icontext.// -->
		<div class="mt-3">
		<h6>{{review.subject}}</h6>
			<p>
				{{review.review}}
			</p>	
		</div>
	{% endfor %}
	</article>

	

	</div> <!-- col.// -->
</div> <!-- row.// -->


</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->


{% endblock content %}

emart/templates/store/store.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg">
<div class="container">
{% if "search" in request.path %}
	<h1 class="title-page">Search Result :</h1>
{% else %}
	<h1 class="title-page">Our Store</h1>
{% endif %}
	
</div> <!-- container //  -->
</section>
<!-- ========================= SECTION INTRO END// ========================= -->

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
<div class="container">

{% if products %}
<div class="row">
	<aside class="col-md-3">
		
<div class="card">
	<article class="filter-group">
		<header class="card-header">
			<a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="true" class="">
				<i class="icon-control fa fa-chevron-down"></i>
				<h6 class="title">Categories</h6>
			</a>
		</header>
		<div class="filter-content collapse show" id="collapse_1" style="">
			<div class="card-body">
				
				<ul class="list-menu">
				<li><a href="{% url 'store' %}">All products</a></li>
				{% for category in links %}
				<li><a href="{{category.get_url}}">{{category.category_name}}</a></li>
				{% endfor %}
				</ul>

			</div> <!-- card-body.// -->
		</div>
	</article> <!-- filter-group  .// -->
	<article class="filter-group">
		<header class="card-header">
			<a href="#" data-toggle="collapse" data-target="#collapse_4" aria-expanded="true" class="">
				<i class="icon-control fa fa-chevron-down"></i>
				<h6 class="title">Sizes </h6>
			</a>
		</header>
		<div class="filter-content collapse show" id="collapse_4" style="">
			<div class="card-body">
			  <label class="checkbox-btn">
			    <input type="checkbox">
			    <span class="btn btn-light"> XS </span>
			  </label>

			  <label class="checkbox-btn">
			    <input type="checkbox">
			    <span class="btn btn-light"> SM </span>
			  </label>

			  <label class="checkbox-btn">
			    <input type="checkbox">
			    <span class="btn btn-light"> LG </span>
			  </label>

			  <label class="checkbox-btn">
			    <input type="checkbox">
			    <span class="btn btn-light"> XXL </span>
			  </label>
		</div><!-- card-body.// -->
		</div>
	</article> <!-- filter-group .// -->
	
	<article class="filter-group">
		<header class="card-header">
			<a href="#" data-toggle="collapse" data-target="#collapse_3" aria-expanded="true" class="">
				<i class="icon-control fa fa-chevron-down"></i>
				<h6 class="title">Price range </h6>
			</a>
		</header>
		<div class="filter-content collapse show" id="collapse_3" style="">
			<div class="card-body">
				
				<div class="form-row">
				<div class="form-group col-md-6">
				  <label>Min</label>
				  <!-- <input class="form-control" placeholder="$0" type="number"> -->
				  	<select class="mr-2 form-control">
						<option value="0">$0</option>
						<option value="50">$50</option>
						<option value="100">$100</option>
						<option value="150">$150</option>
						<option value="200">$200</option>
						<option value="500">$500</option>
						<option value="1000">$1000</option>
					</select>
				</div>
				<div class="form-group text-right col-md-6">
				  <label>Max</label>
				  	<select class="mr-2 form-control">
						<option value="50">$50</option>
						<option value="100">$100</option>
						<option value="150">$150</option>
						<option value="200">$200</option>
						<option value="500">$500</option>
						<option value="1000">$1000</option>
						<option value="2000">$2000+</option>
					</select>
				</div>
				</div> <!-- form-row.// -->
				<button class="btn btn-block btn-primary">Apply</button>
			</div><!-- card-body.// -->
		</div>
	</article> <!-- filter-group .// -->
	
</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<main class="col-md-9">

<header class="border-bottom mb-4 pb-3 ">
		<div class="form-inline ">
			<span class="mr-md-auto ">{{product_count}} Items found </span>
			
		</div>
</header><!-- sect-heading -->

<div class="row">
{% for product in products %}
	<div class="col-md-4">
		<figure class="card card-product-grid">
			<div class="img-wrap"> 
				
				<img src="{{product.image.url}}">
				
			</div> <!-- img-wrap.// -->
			<figcaption class="info-wrap">
				<div class="fix-height">
					<a href="{{product.get_url}}" class="title">{{product.product_name}}</a>
					<div class="price-wrap mt-2">
						<span class="price">${{product.price}}</span><br>
						<span style="color:#ffb503;">
							<i class="fa fa-star{% if product.averagereview >= 0.5 and product.averagereview < 1 %}-half-o{% elif product.averagereview < 0.5 %}-o{% endif %}" aria-hidden="true"></i>
							<i class="fa fa-star{% if product.averagereview >= 1.5 and product.averagereview < 2 %}-half-o{% elif product.averagereview < 1.5 %}-o{% endif %}" aria-hidden="true"></i>
							<i class="fa fa-star{% if product.averagereview >= 2.5 and product.averagereview < 3 %}-half-o{% elif product.averagereview < 2.5 %}-o{% endif %}" aria-hidden="true"></i>
							<i class="fa fa-star{% if product.averagereview >= 3.5 and product.averagereview < 4 %}-half-o{% elif product.averagereview < 3.5 %}-o{% endif %}" aria-hidden="true"></i>
							<i class="fa fa-star{% if product.averagereview >= 4.5 and product.averagereview < 5 %}-half-o{% elif product.averagereview < 4.5 %}-o{% endif %}" aria-hidden="true"></i>
						</span>
						{% comment %} <del class="price-old">$1980</del> {% endcomment %}
					</div> <!-- price-wrap.// -->
				</div>

	{% if product.stock <= 0 %}
    	<h4 class="text-warning">Comming Soon</h4>
    {% else %}
		<h4 class="text-success">Available</h4>
	{% endif %}
			<a href="{{product.get_url}}" class="btn btn-block btn-primary">View Details  <i class="fas fa-shopping-cart"></i>  </a>
			
			</figcaption>
		</figure>
	</div> <!-- col.// -->
{% endfor product %}
{% else %}
	<h2 class="title-page text-center">No products found !<h2> <br><br>
	<h4 class="title-page text-center"> Try proper keywords.</h4>

{% endif %}
</div> <!-- row end.// -->

{% if products.has_other_pages %}
<nav class="mt-4" aria-label="Page navigation sample">
  <ul class="pagination">
  {% if products.has_previous %}
    <li class="page-item"><a class="page-link" href="?page={{products.previous_page_number}}">Previous</a></li>
  {% else %}
    <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
  {% endif %}
  {% for i in products.paginator.page_range %}
  {% if products.number == i %}
    <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
  {% else %}
    <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
  {% endif %}
  {% endfor %}
  {% if products.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{products.next_page_number}}">Next</a></li>
  {% else %}
    <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
  {% endif %}
  </ul>
</nav>
{% endif %}
	</main> <!-- col.// -->

</div>

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->







{% endblock content %}